### ISSUE TITLE
Arabic barjeel site

### ISSUE THREAD

**Issue by clintmclean** [robertocarroll/barjeel#19]
Hi Rob
Is it possible for us to test copying and pasting some text into your plugin thing so we can test it before I meet with Mandy tomorrow? I just want to make sure the text pastes correctly whether it comes from a word doc or pdf or anything else we may need to copy and paste from.

**Comment by robertocarroll** [comment]
Closing this issue as we haven't heard anything for a while. We can re-open if necessary.
