### ISSUE TITLE
Contact and About new staff member

### ISSUE THREAD

**Issue by clintmclean** [robertocarroll/barjeel#37]
1. There is a new staff member at Barjeel named Sarah Gage. I have uploaded a 200px square headshot of her in the media library of wordpress. Can we add her to the site? Here name and title is in the file name (Sarah Gage, Registrar and Collections Manager). It will require reordering the headshots (Sultan, Suheyla, Mandy, Sarah) and moving the address of Barjeel. I think we can put the address on one line left to right above the headshots and below the link to google maps.

2. Lessen space between headshots and their related text by 50%

3. Can we make the link to google maps just open the barjeel location on google maps rather than opening a direction from place A to place Barjeel?

**Comment by robertocarroll** [comment]
3. Please can you provide the link on Google Maps as I can't seem to find the actual location and the lat, long from our Google maps shows something different.

**Comment by clintmclean** [comment]
Here you go.
https://www.google.ae/maps/place/Al+Qasba/@25.322508,55.376222,17z/data=!3m1!4b1!4m2!3m1!1s0x3e5f5b940e79d3ab:0xc9e890682aa4c437?hl=en

**Comment by robertocarroll** [comment]
Done. You can play about with the address format by editing the contact&about page. Or I can do it if you let me know what you would like best.

**Comment by clintmclean** [comment]
Ok sounds good.
Are you working on the downloads page - it looks like the first one is
different than the rest.
