### ISSUE TITLE
Remove Non-Arab art from filter

### ISSUE THREAD

**Issue by clintmclean** [robertocarroll/barjeel#38]
Can we remove the non-arab art from the results when filtering by medium etc? I think that collection should remain totally separate and equally problematic, it knocks the alignment out as soon as a non-arab art shows up since they do not include three lines of text under the preview circle.

**Comment by robertocarroll** [comment]
Why do non-Arab art posts show up there? They would only show up if they were tagged with the medium. Do you have an example?

**Comment by clintmclean** [comment]
Ok I will look into it - probably I have them tagged with medium. I will
untag.

On Sunday, April 19, 2015, Robert Carroll <notifications@github.com> wrote:

> Why do non-Arab art posts show up there? They would only show up if they
> were tagged with the medium. Do you have an example?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/robertocarroll/barjeel/issues/38#issuecomment-94306636>
> .
>


-- 
clint@clintmclean.com
(971) 55 474 8846

**Comment by clintmclean** [comment]
This is now done.
