### ISSUE TITLE
Tweaks to Downloads page

### ISSUE THREAD

**Issue by clintmclean** [robertocarroll/barjeel#39]
1. Can we reduce font size in the text under the thumbnails on this page: http://www.barjeelartfoundation.org/downloads
I would go down two sizes (not sure what our H sizes are here but the text is sometimes quite long so smaller text would be good). If you let me know when you are doing it maybe I can look at it down 1 size and down 2?

2. Center text and image on the individual download page. http://www.barjeelartfoundation.org/download/sultan-sooud-al-qassemi-foreword-marwan-topographies-of-the-soul/

**Comment by robertocarroll** [comment]
1. Reduced the font size on the downloads page/

2. Changed the set-up for a single download. I've done quite a lot of work on this including testing with users and "click to download" is not great, esp since "click" does not exist on many devices. Take a look at the example: http://www.barjeelartfoundation.org/download/sultan-sooud-al-qassemi-foreword-marwan-topographies-of-the-soul/

What do you think? You will need to duplicate the markup in that example post for it to work in other posts.

**Comment by clintmclean** [comment]
Hi - yeah you're right - download as pdf is better. I will change the
others. Can we set that link up below the image though and then center
everything?

**Comment by robertocarroll** [comment]
It does that on smaller screens but don't you think it looks odd on wider screens?

**Comment by clintmclean** [comment]
I think it looks odd on wider screens (laptops anyway) as it really seems
like it wasn't designed for that space. I think without doing something
from scratch centering is our best option. Why do you think it will look
odd?

**Comment by robertocarroll** [comment]
It just looks like it's hanging there in mid air and that's on my small laptop screen. I can't imagine what it looks like on a desktop:

![sultan sooud al qassemi foreword_ marwan - topographies of the soul - barjeel art foundation](https://cloud.githubusercontent.com/assets/1565953/7229187/b3885930-e758-11e4-9382-ad504f74c161.jpg)

**Comment by clintmclean** [comment]
I would center the title text also - it looks like a much more intentional
use of space to me. Could you do one as each of us is suggesting and I will
get Una's thoughts on it?

On Monday, April 20, 2015, Robert Carroll <notifications@github.com> wrote:

> It just looks like it's hanging there in mid air and that's on my small
> laptop screen. I can't imagine what it looks like on a desktop:
>
> [image: sultan sooud al qassemi foreword_ marwan - topographies of the
> soul - barjeel art foundation]
> <https://cloud.githubusercontent.com/assets/1565953/7229187/b3885930-e758-11e4-9382-ad504f74c161.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/robertocarroll/barjeel/issues/39#issuecomment-94428366>
> .
>


-- 
clint@clintmclean.com
(971) 55 474 8846

**Comment by robertocarroll** [comment]
but centering everything is a big deviation from the website design isn't it? It would also mean making a new post type just to centre the title ... 

The current approach follows the established patterns in that everything gets centred on smaller screens ...

**Comment by clintmclean** [comment]
Hi, as a post it would break format yet - but if you ignore that these are
created in 'post', they are not dissimilar to the artwork previews. In
fact, if possible, I think our best option is to go directly from the
preview on the Downloads page directly to the pdf rather than having the
middle step which is unnecessary if it can be avoided. Regardless I don't
think it looks like the second preview page (after the downloads landing
page) was really designed but rather is just the way things fell into place
(which is sort of true).

**Comment by robertocarroll** [comment]
I disagree: the downloads need to be "wrapped" in a post so that they can be searched and linked to and all sorts of other things. The direct download is a bad idea and difficult to implement. 

With regard to how that page looks - I don't really have strong feelings about it. It's taken a lot longer than it should have done already so just let me know so we can wrap this up.

**Comment by clintmclean** [comment]
ok lets center it and call it a day.
Let me know your time on this stuff and I'll make sure you get paid.

**Comment by robertocarroll** [comment]
OK. I've centred it. Closing this issue.

**Comment by clintmclean** [comment]
ok thanks. Can title center too pretty please ; )
(date is fine as is)

**Comment by robertocarroll** [comment]
Not without create a new post type and all the associated stuff. I'll send you an estimate along with the work done so far and you can decide.

**Comment by clintmclean** [comment]
okie dokie
