### ISSUE TITLE
Page template clean up

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/barjeel#42]
- [x] Update page.php
- [x] Delete issue tracker page
- [x] Delete press/media page
- [x] Delete social responsibility page and page-social.php
- [x] Delete page-no-title.php

## Education
- [x] Add custom field: more-post-link = /news-themes/education/
- [x] Add custom field: news-theme = education
- [x] Education page change to default page template
- [x] Delete page-education.php

## On loan
- [x] Overwrite the content of the post (new formatting)
- [x] Add custom field: more-post-link = /news-themes/loans/
- [x] Add custom field: news-theme = loans
- [x] Loans page change to default page template
- [x] Delete page-loans.php

## Press
- [x] Overwrite the content of the post (new formatting)
- [x] Press page change to default page template
- [x] Delete page-press.php

## Downloads
- [x] Delete downloads page 
- [x] Delete page-downloads.php
- [x] Change category name and slug to downloads 
- [x] Add category description
- [x] Upload category-downloads.php
- [x] Change post format to 'download' 
- [x] Each download post needs a custom field 'pdflink'
- [x] Create download posts for each exhibition catalogue

## Catalogue downloads to add
Strike Oppose exhibition catalogue
http://www.barjeelartfoundation.org/wordpress/wp-content/uploads/2012/11/Final_Strike_Oppose_Catalogue.pdf

Caravan exhibition catalogue
http://www.barjeelartfoundation.org/wordpress/wp-content/uploads/2011/10/Caravan-Catalogue_Final.pdf

Alienation exhibition catalogue
http://www.barjeelartfoundation.org/wordpress/wp-content/uploads/2012/03/Alienation_Catalogue_Final.pdf

Re:Orient exhibition catalogue
http://www.barjeelartfoundation.org/wordpress/wp-content/uploads/2014/05/May-17-2014_ReOrient_reprint_final-full-LR.pdf

Tarīqah exhibition catalogue 
http://www.barjeelartfoundation.org/wordpress/wp-content/uploads/2014/02/Tariqah_Final_Catalogue_Full_LR.pdf

Modes and Methods exhibition catalogue 
http://www.barjeelartfoundation.org/wordpress/wp-content/uploads/2014/05/google-catalogue-May17-final-LR.pdf

aide-mémoire exhibition catalogue
http://www.barjeelartfoundation.org/wordpress/wp-content/uploads/2015/01/Aide_Memoire_image_cards_final_nov25b-LR.pdf

footnotes exhibition catalogue 
http://www.barjeelartfoundation.org/wordpress/wp-content/uploads/2015/03/footnotes-21x24-final.pdf

Topographies of the Soul exhibition catalogue
http://www.barjeelartfoundation.org/wordpress/wp-content/uploads/2015/01/Marwan-Catalog..pdf

Press kit
http://www.barjeelartfoundation.org/wordpress/wp-content/uploads/2013/03/Barjeel-Press-Kit.zip

**Comment by robertocarroll** [comment]
Going through these pdfs for downloads, I do have to ask why they are pdfs and "downloads". Why aren't they on the site in a format which is readable and searchable instead of locked away in pdfs?

**Comment by robertocarroll** [comment]
Also the dates seem to need fixing on these posts. All the ones I've done so far are 31 March 2015.

**Comment by robertocarroll** [comment]
The exhibition catalogues need better images. Not sure if you can finish this off when you get chance.

**Comment by clintmclean** [comment]
Not sure what you mean by better images. For the thumbnail covers you mean? 

What format would  you suggest to make the catalogues readable and searchable. The pdf download is meant to make them a convenient resource that isn't tied to the website, but that's not to say we can't have them readable and searchable as well.

**Comment by robertocarroll** [comment]
- I think you've done the thumbnail thing. 
- I meant why aren't the articles added as text on the website rather than only as pdfs? 

I'm going to close this issue as I think we've completed all the tasks.
