### ISSUE TITLE
Trim down the number of images in slideshows

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/barjeel#45]
There's too many images in a lot of the slideshows and it is causing a long delay in page loading. If possible it would be great if we could reduce the number of slides to >10 or even 7 or 8.

**Comment by clintmclean** [comment]
I spoke to Suheyla about this and she is fine with us cutting down images and will let Sultan know of our intentions.

**Comment by clintmclean** [comment]
Have limited new slideshows to max of 10 and will go through old ones and remove excess.
