### ISSUE TITLE
Structured data for contact

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/barjeel#47]
This markup was structured data for the address, but it was removed on 20 April. Can we add it back in?

```
<div class="padding-bottom" itemscope itemtype="http://schema.org/Organization"><span itemprop="name" class="uppercase">Barjeel Art Foundation, </span><span itemprop="address" itemscope itemtype="http://schema.org/PostalAddress"><span itemprop="streetAddress">Level Two Maraya Art Centre, Al Qasba, </span><span itemprop="addressLocality">Sharjah, UAE</span></span><span itemprop="telephone"> + 971 6 556 6555 </span><span itemprop="email"> info(at)barjeelartfoundation.org</span><a href="https://www.google.ae/maps/place/Al+Qasba/@25.322508,55.376222,17z/data=!3m1!4b1!4m2!3m1!1s0x3e5f5b940e79d3ab:0xc9e890682aa4c437?hl=en"> Open in Google Maps</a></div>
```

**Comment by clintmclean** [comment]
Hi, I don't know what you mean by 'structured data'. That info is on the contact page so I'm not sure what is missing - wasn't it just the styling of the text that changed?

**Comment by robertocarroll** [comment]
I made the markup so that it conformed to the http://schema.org/ structure for address so that search engines and other machines parse it easily. That was on 20 April, but then on 20 April you seem to have taken it all out again. Would you mind if I put it back in?

**Comment by clintmclean** [comment]
I did? sorry! I don't recall doing it but I guess I did…
So it doesn't effect the styling of the text? Yeah go ahead and add it back in - sorry again.
C.

**Comment by robertocarroll** [comment]
Sorry! It's odd. I don't think it was you. WordPress seems to take out that markup when you save the post.

**Comment by robertocarroll** [comment]
Going to have to add this in during the next maintenance: 
https://snipt.net/jamesw/prevent-tinymce-from-stripping-schemaorg-attributes-in-wordpress/

(Leaving this issue open until I do.) Sorry for the false accusation!

**Comment by robertocarroll** [comment]
https://gist.github.com/uxjw/b812fd9c169eec94719b

**Comment by robertocarroll** [comment]
Not going to do this one.
