### ISSUE TITLE
Curated selections menu

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/barjeel#48]
Need to change this to accommodate:

- Modern masterpieces
- Contemporary highlights

But there's some kind of issue on large screens.

**Comment by robertocarroll** [comment]
Here's what it looks like at the moment on the local dev:
![collection___barjeel_art_foundation](https://cloud.githubusercontent.com/assets/1565953/9661937/f4880d74-5254-11e5-9388-b44f3c175d87.png)

**Comment by robertocarroll** [comment]
Hang on. I see.

**Comment by robertocarroll** [comment]
OK. That seems to work now. Closing this issue. Please re-open if there are any more problems.

**Comment by clintmclean** [comment]
Thanks Rob!
