### ISSUE TITLE
New social media icons

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/barjeel#51]
![icons-barjeel_720](https://cloud.githubusercontent.com/assets/1565953/12782023/3c98636e-ca70-11e5-864b-f891f0f86345.jpg)

Using sprites provided and layout above.

**Comment by robertocarroll** [comment]
I've added these and the links. Please can you provide a x2 sprite (like the one attached). The others did not have any space between the icons so there were problems with edges getting cut off. Thanks.

![social-icon-sprite](https://cloud.githubusercontent.com/assets/1565953/12793793/15daa932-caaa-11e5-9177-550ad37bef7b.png)

**Comment by clintmclean** [comment]
Can we spread these out on the site as in the pdf above?

**Comment by robertocarroll** [comment]
Sure - I will do the spacing and the retina version. Do you think there's a bit of inconsistency with the design: the search button seems to come from a different site and it gradually hovers red.

**Comment by robertocarroll** [comment]
We're going to try https://github.com/filamentgroup/grunticon for all our icons - svg with a png backup for older browsers.

**Comment by robertocarroll** [comment]
Updated with new hovers.

**Comment by robertocarroll** [comment]
Just leaving a note here: there's something odd about SVGs where you can't style them with CSS if you add them using CSS background. So I've used the hover states and toggle between them with a fade. Same with pngs for older browsers.
