### ISSUE TITLE
Integrate google museum view

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/barjeel#52]
Code:
`<iframe allowfullscreen frameborder="0" width="800" height="600" src="https://embed.culturalspot.org/embed/asset-viewer/BQGa_YmzgTSl8w"></iframe>`

Aspect ratio is 8x6. Needs a custom CSS to wrap it in.

**Comment by robertocarroll** [comment]
I've added a class called interactiveWrapper which works like the video one but at 8:6 ratio. It seems to work OK, but I'm not sure the Google thing likes going small.

**Comment by clintmclean** [comment]
Not sizing to fit my phone - maybe that is more of a 4s problem than widespread problem. Will ask Una to try it on her iphone 6.

**Comment by clintmclean** [comment]
I'm attaching a couple screen shots here from my computer using firefox and from Sarah's (at barjeel) computer using Chrome. Both of these browsers are up to date though it looks fine on my Chrome which is also up to date.
<img width="994" alt="screen shot 2016-02-07 at 12 27 38" src="https://cloud.githubusercontent.com/assets/4203246/12872049/5a72fb64-cd96-11e5-8824-4605ac4cd7e3.png">
![screen shot 2016-02-07 at 11 58 16 am](https://cloud.githubusercontent.com/assets/4203246/12872051/7596eb8a-cd96-11e5-95f5-6d07625199de.png)

**Comment by robertocarroll** [comment]
I can't see any reason why the responsive iFrame isn't working, but even when it does it doesn't size nicely on a mobile. So even without all these glitches, it wouldn't be great. Is there any reason why we can't just link to it rather than embed it?

**Comment by robertocarroll** [comment]
If you go to the tour on their site on a phone, they provide a different experience to the desktop. So it's not just a matter of resizing a single iframe. Did Google not provide any guidance?

**Comment by robertocarroll** [comment]
Also something I worked on for another project was http://blog.apps.npr.org/pym.js/ which allows responsive iFrames. Could be worth trying out if they have the budget?

**Comment by clintmclean** [comment]
Google provided this original iframe and I don't see us going back to this so am going to close the issue.
