### ISSUE TITLE
Press icon alignment

### ISSUE THREAD

**Issue by clintmclean** [robertocarroll/barjeel#54]
Could we align the icon to the bottom of the baseline (so the bottom of the icon aligns with the bottom of the text it is connected to).

**Comment by robertocarroll** [comment]
Need to change the class:

`.inline-icon {
    margin-bottom: 2px;
    margin-right: 6px;
    vertical-align: bottom;
}`

**Comment by robertocarroll** [comment]
Aligned bottom now. Closing this issue. http://www.barjeelartfoundation.org/exhibitions/re-orient/
