### ISSUE TITLE
Artist pages not always including the associated artists artworks

### ISSUE THREAD

**Issue by clintmclean** [robertocarroll/barjeel#61]
- [ ] Artist pages not always including the associated artists artworks and some feature an image above and others don't (maybe we discussed that - do I need to do something there?)
![screen shot 2017-04-04 at 11 19 30 am](https://cloud.githubusercontent.com/assets/4203246/24954540/1f392f86-1f80-11e7-96a4-bade16bd5449.png)
![j hadjithomas k joreige](https://cloud.githubusercontent.com/assets/4203246/24954555/2a08fb9e-1f80-11e7-9152-fb37612c61d9.png)

**Comment by robertocarroll** [comment]
Can you remember how this is meant to work? 

http://www.barjeelartfoundation.org/artist/egypt/ezekiel-baroukh/

It's something to do with the slug in the url, but I can't remember where it gets it from. Anyway, can you see how the slug on the artist page is `ezekiel-baroukh` but the name of the artist is Ezequiel Baroukh.

I need to look into how it works but this difference must be something to do with it. Like the artworks have a different slug to the artist ...

**Comment by clintmclean** [comment]
Sorry didn’t attach the Morsi examples.

C.

**Comment by clintmclean** [comment]
The slug is from me when I create the page.Sometimes spellings differ because as different exhibitions or whatever happen, I get sent a different spelling and when I confirm with barjeel which it is, sometimes it is the new spelling but the page is made with the old spelling. So I change all but the slug. That shouldn’t matter should it? The artist name for the page I think comes from the artist category that is linked to the country…right?

**Comment by robertocarroll** [comment]
The slug is the connection. I just can't remember how it all works. Need to dig into it again, but it definitely uses the slug to match something ...

**Comment by robertocarroll** [comment]
What's wrong with Morsi? He only has one artwork and it's showing OK.

**Comment by clintmclean** [comment]
Also - I am going to have a skype with mandy and suheyla and marah all at once and go over all the odds and ends as well as talk process. I”ll ask about the app at this time. I”ll make a list of stuff I will go over with them and you can see if there is anything else to add.

**Comment by robertocarroll** [comment]
I could do with a list of all the artist problems. I don't think there's going to be a single answer / over-all tech issue.

**Comment by robertocarroll** [comment]
Are they happy? I sense they are a bit pissed off with us. Is that true?

**Comment by robertocarroll** [comment]
Notes: 

Used this to log out the result of the get_queried_object

```
<?php
            $a= get_queried_object()->name;
              echo '<script>console.log("Name: ' . $a  . '")</script>';

            $b= get_queried_object()->slug;
            echo '<script>console.log("Slug: ' .  $b . '")</script>';
         ?>
```

Looking at https://codex.wordpress.org/Class_Reference/WP_Query#Taxonomy_Parameters

`$taxonomy_name = get_queried_object()->name;` should really be `$taxonomy_name = get_queried_object()->slug;` because we are looking for the slug in the tax_query

```
array(
          'taxonomy' => 'artist',
          'terms' => array($taxonomy_name),
          'field' => 'slug',
        )
```

**Comment by robertocarroll** [comment]
Also it seems like WordPress started adding keywords to slugs for SEO. I've changed a setting in the SEO plugin that should stop it from now on.

**Comment by robertocarroll** [comment]
@clintmclean needs to go through and check the slugs on artists added since this change came in.

**Comment by clintmclean** [comment]
This is now done.
