### ISSUE TITLE
Show more than one exhibition on artists page

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/barjeel#67]
- Looking at the custom field in each post 
- Need to pull in all the custom fields - an array 
- From all posts - an array 
- Remove any duplicates
- Show the links

**Comment by robertocarroll** [comment]
Working now, but I had to put the artworks above the meta data because I had to pull the metadata off each artwork. I think this is OK, but let me know what you think.

## More than one image

![test_artist_1___barjeel_art_foundation](https://cloud.githubusercontent.com/assets/1565953/25553824/bcd603c6-2cce-11e7-99dc-caef83a07911.png)

## One image

![test_artist_1___barjeel_art_foundation](https://cloud.githubusercontent.com/assets/1565953/25553880/59afd978-2cd0-11e7-8f46-96d7eb56c55a.png)

**Comment by clintmclean** [comment]
I’m still only seeing one exhibition listed on anyone’s artist page.
I think the layout on this is fine except when there are lots of artworks, then you won’t see any of the text right?
Once there are 7 or more artworks I think it will push the text ‘below the fold’ so to speak.

C.

**Comment by clintmclean** [comment]
Also - i just noticed when I click on the one exhibition that does show up, it says page not found.

**Comment by robertocarroll** [comment]
Some of the links to exhibitions are a bit wrong. I think it needs to be:

`/exhibitions/lines-of-subjectivity-portrait-and-landscape-paintings/`

But it's actually: 

`http://www.barjeelartfoundation.org/artist/egypt/ezequiel-baroukh/wordpress/exhibitions//lines-of-subjectivity-portrait-and-landscape-paintings/`

You need to put a / in the front to make it start from the site root and you need to take out /wordpress/

(I think ... you might want to try one before you fix them all up.)

**Comment by clintmclean** [comment]
Exhibition links from artist pages not leading to the exhibition page.
Looks like they are using the artist name in the slug which is probably causing problems.
http://www.barjeelartfoundation.org/artist/syria/abdalla-omari/wordpress/exhibitions/chefs-doeuvre-de-lart-moderne-et-contemporain-arabe/

**Comment by clintmclean** [comment]
Can we change the word Country to say Origin so it matches the artwork page for that same taxonomy_

**Comment by robertocarroll** [comment]
The problem is an input error not a technical error. 

Artwork Barack has this in the exhibition custom field:

`<a href="wordpress/exhibitions/chefs-doeuvre-de-lart-moderne-et-contemporain-arabe/">Chefs-D’œuvre de L’art Moderne et Contemporain Arabe</a>`

The lack of a slash at the front `a href="wordpress` means that the link will go from the current page. So you are on this page: 

http://www.barjeelartfoundation.org/artist/syria/abdalla-omari

and you are then adding this to the current link: `wordpress/exhibitions/chefs-doeuvre-de-lart-moderne-et-contemporain-arabe`

Resulting in `http://www.barjeelartfoundation.org/artist/syria/abdalla-omari/wordpress/exhibitions/chefs-doeuvre-de-lart-moderne-et-contemporain-arabe/`

**Comment by robertocarroll** [comment]
The actual link to that exhibition is: 

`http://www.barjeelartfoundation.org/exhibitions/chefs-doeuvre-de-lart-moderne-et-contemporain-arabe/`

so (I think) the custom field needs to be: 

`<a href="/exhibitions/chefs-doeuvre-de-lart-moderne-et-contemporain-arabe/">Chefs-D’œuvre de L’art Moderne et Contemporain Arabe</a>`

but you need to check it before you go and fix them all up.

**Comment by robertocarroll** [comment]
(Actually I've just done it for that one and it works)

**Comment by clintmclean** [comment]
working from this page also so... my mistake!

**Comment by clintmclean** [comment]
http://www.barjeelartfoundation.org/collection/abdul-qader-al-rais-untitled-5/

**Comment by clintmclean** [comment]
Just checking - the page above which is working and I think the format we've been doing (I always copy and paste previous exhibition urls to make the new ones) includes 'wordpress'. It is not necessary though right? You'd rather I don't include as in this example: <a href="wordpress/exhibitions/the-sea-suspended/">The Sea Suspended</a>

**Comment by clintmclean** [comment]
...doesn't let me past the url <a href="wordpress/exhibitions/the-sea-suspended/">The Sea Suspended</a>

**Comment by clintmclean** [comment]
href="wordpress/exhibitions/the-sea-suspended/">The Sea Suspended</a>

**Comment by clintmclean** [comment]
I think this is all sorted so will close. Let me know if anything is remaining.
