### ISSUE TITLE
Allow artist names more space on artwork page

### ISSUE THREAD

**Issue by clintmclean** [robertocarroll/barjeel#69]
Currently the letters max out at the same number of letters as in the circle thumbnails. The artwork pages have space for full names to show without the ... cutting them off.

http://www.barjeelartfoundation.org/artist/bahrain/abdullah-al-muharraqi/
http://www.barjeelartfoundation.org/collection/the-impaling-stake-abdullah-al-muharraqi/

Same on the search result page
http://www.barjeelartfoundation.org/?s=muharraqi

**Comment by robertocarroll** [comment]
I've increased the character limit to 100 characters (from 20). It would be quite a lot of work to make it do something in one situation and do something else in another. Let me know if there's appetite and budget for such an approach.

**Comment by robertocarroll** [comment]
Closing. Feel free to re-open if it's still an issue.
