### ISSUE TITLE
Changes - May 11, 2017

### ISSUE THREAD

**Issue by clintmclean** [robertocarroll/barjeel#71]
- [x] Remove the “Born in ” taxonomy and only keep country taxonomy

- [x] On artwork page, add taxonomy for year

- [x] show up to 18 exhibitions on exhibitions home page (same number as artworks on collection home page)

- [x] Increase text size of text at top of these pages:  Press / Private Collection / Downloads page
same size on each - what is good size? What are they now?

- [ ] Question: On Artist Pages, can we (or would we) add 'See More' option to load the artworks after two rows of artworks so rather than 'Details' it would be Name, 6 artworks and then info and text. If there are more than 6 artworks, you could click to See More and the page would expand. ...I assume this is not a good (or possible idea) but we then need to come up with alternative.

**Comment by robertocarroll** [comment]
Did the artist pages issue ever get resolved?

**Comment by robertocarroll** [comment]
We've picked this up in #81 so closing this issue.
