### ISSUE TITLE
On artwork page, add taxonomy for year

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/barjeel#74]

**Comment by robertocarroll** [comment]
When you implement this in production, don't forget to update permalinks - Settings > Permalinks > Save Changes (without modification)

**Comment by robertocarroll** [comment]
I've added this. If the taxonomy page isn't working, see above for the probable solution.

**Comment by clintmclean** [comment]
Great. Please can you move it to after the artwork title so it relates to the artwork rather than the artist.

**Comment by clintmclean** [comment]
This works great on the artwork page but when you click the year it takes you to Page Not Found.

**Comment by robertocarroll** [comment]
> When you implement this in production, don't forget to update permalinks - Settings > Permalinks > Save Changes (without modification)

**Comment by robertocarroll** [comment]
Working now.
