### ISSUE TITLE
Check title font sizes and standardise

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/barjeel#76]
> Increase text size of text at top of these pages: Press / Private Collection / Downloads page
same size on each - what is good size? What are they now?

**Comment by robertocarroll** [comment]
This is body text on the description - Make it bigger (one size up from downloads) and matching.

**Comment by clintmclean** [comment]
Can you match Art Loans to the same size/shade you used for these others please?

**Comment by robertocarroll** [comment]
> Can you match Art Loans to the same size/shade you used for these others please?

Done.
