### ISSUE TITLE
Exhibitions date taxonomy

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/barjeel#77]
We discussed a way of using taxonomies instead of custom fields for the dates of exhibitions. It does seem a shame to have that information but not be able to use it programmatically. 

It would a bit more complex to implement because it is two fields (from and to), so we would need confirmation to go ahead with this enhancement.

**Comment by clintmclean** [comment]
Lets leave this as is. The exhibitions are already chronological anyway.
