### ISSUE TITLE
About - new layout

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/barjeel#79]
Using designs provided.

**Comment by robertocarroll** [comment]
Done. Need to remember that The address section appears twice in the code, but only shows once depending on the viewport width.

If the address block gets updated, remember to do it in two places on the same page.

**Comment by clintmclean** [comment]
• Address appears twice on mobile (once above the About text and once below) and does not have the box around it.
•Double check the box is in barjeel blue
• Make About text as large as the address text (I'm not super sure about this - I had it larger than the address text in my design but didn't have pt. sizes for existing website text. I think it would look better bigger though! If I am around when you do it maybe i can look as  you do?

**Comment by robertocarroll** [comment]
> Address appears twice on mobile (once above the About text and once below) and does not have the box around it.

I think you need to clear your cache. 

> Double check the box is in barrel blue

Yep $barjeel-blue: #66BBDD;

> Make About text as large as the address text (I'm not super sure about this - I had it larger than the address text in my design but didn't have pt. sizes for existing website text. I think it would look better bigger though! If I am around when you do it maybe i can look as  you do?

I've increased it to $h4-size:  18px!default; // .delta

**Comment by clintmclean** [comment]
I think maybe you made the address text larger rather than the About text no?

**Comment by robertocarroll** [comment]
Ah yes I did. You wanted it the other way around?
